name: Build

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'

env:
  BLOONSTD6: ./BloonsTD6
  PROJECT_NAME: AutoEscape
  MOD_HELPER_BRANCH: 3.0_Features

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@master
        with:
          path: ${{ env.PROJECT_NAME }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x # net6 can still build older as well

      - name: Download MelonLoader
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          run_id: 2646562782
          name: MelonLoader.x64.CI.Release
          repo: LavaGang/MelonLoader
          path: ${{ env.BLOONSTD6 }}

      - name: Clone Dependencies Repo
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: doombubbles/btd6-ci-dependencies
          ref: main
          path: ${{ env.BLOONSTD6 }}/MelonLoader/Managed

      - name: Download Mod Helper
        uses: dsaltares/fetch-gh-release-asset@master
        if: env.MOD_HELPER_BRANCH == 'master'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: gurrenm3/BTD-Mod-Helper
          file: BtdModHelper.dll
          target: ${{ env.BLOONSTD6 }}/Mods/

      - name: Download Mod Helper
        uses: dawidd6/action-download-artifact@v2
        if: env.MOD_HELPER_BRANCH != 'master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          name: BtdModHelper.dll
          branch: ${{ env.MOD_HELPER_BRANCH }}
          repo: gurrenm3/BTD-Mod-Helper
          path: ${{ env.BLOONSTD6 }}/Mods/

      - name: Download btd6.targets
        uses: wei/wget@v1
        with:
          args: https://raw.githubusercontent.com/gurrenm3/BTD-Mod-Helper/${{ env.MOD_HELPER_BRANCH }}/BloonsTD6%20Mod%20Helper/btd6.targets

      - name: Build
        run: dotnet build -c Release -p:BloonsTD6="../${{ env.BLOONSTD6 }}" "${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj"

      - name: Upload Mod DLL
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ env.PROJECT_NAME }}.dll
          path: ${{ env.BLOONSTD6 }}/Mods/${{ env.PROJECT_NAME }}.dll
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with: 
          files: ${{ env.BLOONSTD6 }}/Mods/${{ env.PROJECT_NAME }}.dll
          body: ${{ env.PROJECT_NAME }}/LATEST.md
          fail_on_unmatched_files: true